apiVersion: v1
kind: Pod
metadata:
  name: amazonlinux
spec:
  containers:
  - name: amazonlinux
    image: amazonlinux:2
    command: ["/bin/bash"]
    args: ["-c", "echo us-east-2 > /etc/yum/vars/awsregion; yum update; yum install -y tar make; while true; do echo hello; sleep 10; done"]
    volumeMounts:
    - mountPath: /Users
      name: home-volume
  volumes:
  - name: home-volume
    hostPath:
      path: /Users
      type: Directory
