[project]
name = "emr-more-packages"
version = "2024.10.22"
description = "Install more packages to EMR"
authors = [{name="Dyno Fu" , email="dyno.fu@gmail.com"}]
requires-python = ">=3.11"
dependencies = [
    "absl-py>=2.1.0",
    "aiohttp>=3.10.10",
    "aiomultiprocess>=0.9.1",
    "attrs>=24.2.0",
    "boto3>=1.35.44",
    "cattrs>=24.1.2",
    "fastavro>=1.9.7",
    "findspark>=2.0.1",
    "httpie>=3.2.3",
    "invoke>=2.2.0",
    "pandas>=2.2.3",
    "polars>=1.9.0",
    "psycopg2-binary>=2.9.10",
    "pyarrow>=17.0.0",
    "pyhive[hive-pure-sasl]>=0.7.0",
    "pyjwt>=2.9.0",
    "pysasl>=1.2.0",
    "pyyaml>=6.0.2",
    "requests>=2.31.0",
    "s3fs>=0.4.2",
    "sh>=2.1.0",
    "simple-salesforce>=1.12.6",
    "smart-open>=7.0.5",
    "sqlformat>=0.1.3",
    "sqlparse>=0.5.1",
    "tabulate>=0.9.0",
    "tqdm>=4.66.5",
    "trino>=0.330.0",
    "yq>=3.4.3",
]

[tool.uv]
dev-dependencies = [
    "isort>=5.13.2",
    "pytest>=8.3.3",
    "ruff>=0.7.0",
]

[tool.ruff]
line-length = 128
