[project]
name = "emr-more-packages"
version = "2024.10.19"
description = "Install more packages to EMR"
authors = [{name="Dyno Fu" , email="dyno.fu@gmail.com"}]
requires-python = "~=3.7"
dependencies = [
    "absl-py>=2.1.0",
    "aiohttp>=3.8.6",
    "aiomultiprocess>=0.9.0",
    "attrs>=24.2.0",
    "boto3>=1.7.84,<1.25",
    "cattrs>=23.1.2",
    "fastavro>=1.8.0",
    "findspark>=2.0.1",
    "httpie>=3.2.3",
    "invoke>=2.2.0",
    "kubernetes>=31.0.0",
    "pandas>=1.1.5",
    "polars>=0.18.4",
    "psycopg2-binary>=2.9.9",
    "pyarrow>=12.0.1",
    "pyhive[hive-pure-sasl]>=0.7.0",
    "pyjwt>=2.8.0",
    "pysasl>=1.2.0",
    "pyyaml>=6.0.1",
    "requests>=2.31.0",
    "s3fs>=0.2.0",
    "sh>=1.14.3",
    "simple-salesforce>=1.12.6",
    "smart-open>=7.0.5",
    "sqlformat>=0.1.3",
    "sqlparse>=0.4.4",
    "tabulate>=0.9.0",
    "tqdm>=4.66.5",
    "trino>=0.327.0",
    "urllib3<=1.27",
    "yq>=3.4.2",
]

[tool.uv]
dev-dependencies = [
  "isort>=5.11.5",
  "pytest>=7.4.4",
  "ruff>=0.7.0",
]

[tool.ruff]
line-length = 128
